### ISSUE TITLE
Online tool

### ISSUE THREAD

**Issue by En-J-A** [lexmen318/metaCAT#4]
I need to access the tool. Is there an online link ?? if not, how can I run it?
I installed MongoDB and stoped because I found some difficulties in your explanation.

**Comment by lexmen318** [comment]
(Sorry to reply so late)
Do you mean sth. wrong with following scripts?
.......................................
MongoDB User Settings

use metacat
db.createUser({user:'metacat',pwd:'metacat',roles:[{role:"readWrite",db:"metacat"}]})
db.auth("metacat", "metacat")
db.metacat.insert({"name":"metaCAT annotation"})
.......................................
It is general script running in Mongo Shell to initialize DB user.

**Comment by En-J-A** [comment]
I couldn't run it. where can I write that script?
and Is your tool run on scripts in another language like Arabic for example?

**Comment by lexmen318** [comment]
After Mongo is installed, input "mongo" in Linux bash or Windows power shell,  then the Mongo Shell Running Environment is opened. So you can run the above scripts here.

metaCAT is independent of any local languages.
